### ISSUE TITLE
Issue with stitching tiled images

### ISSUE THREAD

**Issue by Eddymorphling** [SebastienTs/MosaicExplorerJ#2]
Hello Sebastien,
I have been in the hunt for finding a tool that will allow me to stich and export large tiled datasets in a quick and easy way. I recently saw MosaicExplorerJ and have been learning on how to use it to stich/register tiled datasets acquired with a ligthsheet. I have been watching the tutorials and have read the documentation as well. 

Initially, to keep it simple, I have been testing the tile/stitch tool on one of my 1x1 tiled dataset. Each tile is 1920x1920 pixels, has 2 channels, 560 z slices and have taken with a single camera. I have been saving files as individual 3D-stacks and have been following the naming convention as shown below. 

![image](https://user-images.githubusercontent.com/67712116/127337490-a5e95a13-a7cc-43c7-a1a8-11429377b7a0.png)

Yet, when I try to import them onto MosaicExplorerJ I can only see the first tile but not the second tile. Am I doing anything wrong? Any suggestions would be appreciated! Thank you.

**Comment by Eddymorphling** [comment]
Ok. I just noticed that I messed the naming of the files. It should be ---C00 and --C01. Now when I try to open the above dataset, I get the following error code on ImageJ
<img width="490" alt="1" src="https://user-images.githubusercontent.com/67712116/127384410-ba2d2df8-7a66-4e80-b324-ed4a79534975.PNG">

And my input parameters are 
<img width="164" alt="2" src="https://user-images.githubusercontent.com/67712116/127384437-07194f13-feec-4dd7-b20e-1118377f9a4f.PNG">

Am I doing something wrong again?

**Comment by SebastienTs** [comment]
Indeed, and you also got the --Y wrong :) As indicated in the documentation, you need to comply to all these delimiters and if they do not match your file naming you can configure them in the macro code (XString, YString, CString and RLString).

**Comment by Eddymorphling** [comment]
Thanks, for spotting that one! I have now corrected the files names but still get the same macro error mentioned above.

**Comment by SebastienTs** [comment]
What if you set Tile width and Tile height to 1920 pixels (not the default 2048 pixels) to match the size of your images?
Assuming that your files are multi-TIFF images with the extension .tif it should then work!

**Comment by Eddymorphling** [comment]
I tried that but with no luck. If I turn on "Auto-detect" it shows up the error. But if I manually set up the x,y,z and c bounds then it works. Yet, it only shows one of the tiles in the image that gets open but it is missing the second tile.

**Comment by SebastienTs** [comment]
I recommend that you then to go step by step and first download the smallest test dataset (12 GB, 2x2 mosaic).
When this one works try to assess the difference between your own image stacks and the ones from this test dataset.
If you prefer, I can also have a look at your dataset if you share it with me since from this point it is hard to tell what might be going wrong without the files!

**Comment by Eddymorphling** [comment]
I figured it out! I was setting up the x,y,z and c bounds incorrectly. Just had to adjust these.

The images that open up always look oversaturated even though I set it the Max Int to the full range in the "Control panel". I getover this by manually tweaking the "Brightness/contrast tool" in ImageJ. This is the same issue if you open the image with or without "Color mode".

**Comment by SebastienTs** [comment]
Good! It should however works perfectly in auto detect mode as well (except if you have other files in the same folder).
About the contrast, I remember a user having this issue with a specific version of ImageJ. My recommendation is to always use the version mentioned in the first section of the documentation. If you have to fiddle with IJ B&C you are not on the good track as these settings will always be overwritten (especially for multi-channel datasets)...

**Comment by Eddymorphling** [comment]
Got it! I will try that. Thanks Sebastian! This has been very helpful.

**Comment by SebastienTs** [comment]
No problem, I am glad that you could get started with your images, do not hesitate to ask again if you get stuck somewhere else!

**Comment by Eddymorphling** [comment]
Thanks. Just a quick question. When exporting the aligned file, it exports each z-slice from each channel as a single TIFF file. Is it possible to export the entire z-volume of every channel as a single TIFF stack?

**Comment by SebastienTs** [comment]
Short answer: no.
Just trying to avoid huge files there.
S.
